### ISSUE TITLE
Counting microsecond intervals

### ISSUE THREAD

**Issue by AnatolSher** [winnermicro/wm_iot_sdk#1]
### ✅ Pre-submission Checklist

- [X] 📖 I have thoroughly reviewed the relevant sections of the [WM_IoT_SDK Programming Guide](https://doc.winnermicro.net/w800/en/latest/) documentation but have not found a solution to my issue.
- [X] 🔄 I have updated my wm_iot_sdk branch (master or release) to the latest version and confirmed that the issue still exists.
- [X] 🔍 I have searched through the [Issues](https://github.com/winnermicro/wm_iot_sdk/issues) and [Discussions](https://github.com/winnermicro/wm_iot_sdk/discussions) sections but have not found a similar issue.

### 📝 Issue Details

Hi! This function should be rewritten like this :

void udelay(uint32_t us)
{
    
    if (us > WM_CLK_MS_UNIT) {
        mdelay(us / WM_CLK_MS_UNIT);
        us = us % WM_CLK_MS_UNIT;
    }

    if (us == 0) {
        return;
    }

    _delay(us);
}

Because I have often encountered the problem of rtos hanging if I call _delay() function with parameter more than 1000

**Comment by samwise-thomas** [comment]
Thank you for your feedback 😊. We have already taken note of the issue with the old version SDK. The _delay interface has been optimized and adjusted in the new version v2.2-beta.2. Please use the latest SDK version v2.2-beta.2 for testing to confirm whether the issue has been resolved. Thank you.

**Comment by AnatolSher** [comment]
Yes, it works stable. But I'll figure something out :)
#include "Arduino.h"

int count = 0;

void setup()
{
}

void loop()
{
    printf("Count = %d \n\r",count);
    count ++;
    udelay(5000000);
}

**Comment by WinnerMicroUser** [comment]
Based on the "hello_world" example, I have followed your method and it has been running stably for a full two days.
```
int count = 0;

static void test_task(void *parameters)
{
    while (1) {
        // wm_log_info("hello world.");

        // vTaskDelay(pdMS_TO_TICKS(1000));
        printf("Count = %d \n\r",count);
        count ++;
        udelay(5000000);
    }

    vTaskDelete(NULL);
}

int main(void)
{
    xTaskCreate(test_task, "test", 512, NULL, 5, NULL);

    return 0;
}
```
